replicaCount: 1
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
resources: {}
livenessProbe:
  httpGet:
    path: /readyz
    port: http
readinessProbe:
  httpGet:
    path: /livez
    port: http
