apiVersion: v1
kind: Service
metadata:
  name: {{ include "gopi.fullname" . }}
  labels:
    {{- include "gopi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gopi.selectorLabels" . | nindent 4 }}
