apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-ratelimit-metrics.serviceAccountName" . }}
  labels:
    {{- include "github-ratelimit-metrics.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  github.app.id: {{ required "secret.githubAppID is required" .Values.secret.githubAppID | toString | b64enc }}
  github.installation.id: {{ required "secret.githubInstallationID is required" .Values.secret.githubInstallationID | toString | b64enc }}
  github.private.key: {{ required "secret.githubPrivateKey is required" .Values.secret.githubPrivateKey | toString | b64enc }}
