apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debug-playground.fullname" . }}
  labels:
    {{- include "debug-playground.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "debug-playground.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "debug-playground.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "debug-playground.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              readOnly: true
              subPath: index.html
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
              subPath: default.conf
      volumes:
        - name: index
          configMap:
            name: {{ include "debug-playground.fullname" . }}
            items:
              - key: index.html
                path: index.html
        - name: conf
          configMap:
            name: {{ include "debug-playground.fullname" . }}
            items:
              - key: default.conf
                path: default.conf
