apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debug-playground.fullname" . }}
  labels:
    name: {{ include "debug-playground.fullname" . }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "debug-playground.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "debug-playground.fullname" . }}
    spec:
      serviceAccountName: {{ include "debug-playground.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources: {}
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              readOnly: true
              subPath: index.html
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
              subPath: default.conf
      volumes:
        - name: index
          configMap:
            name: z{{ include "debug-playground.fullname" . }}
            items:
              - key: index.html
                path: index.html
        - name: conf
          configMap:
            name: z{{ include "debug-playground.fullname" . }}
            items:
              - key: default.conf
                path: default.conf
