apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debug-playground.fullname" . }}
  labels:
    name: {{ include "debug-playground.fullname" . }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
  replicas: 0
  selector:
    matchLabels:
      name: {{ include "debug-playground.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "debug-playground.fullname" . }}
    spec:
      nodeSelector:
        microsoft.ai/reserved-id: abcd1337
      serviceAccountName: {{ include "debug-playground.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "dokcer.io/library/nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /
              port: http
              scheme: HTTPS
          resources:
            requests:
              cpu: 32
              memory: 64Gi
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              readOnly: true
              subPath: index.html
      volumes:
        - name: index
          configMap:
            name: z{{ include "debug-playground.fullname" . }}
            defaultMode: 200
            items:
              - key: index.html
                path: index.html
