apiVersion: v1
kind: Service
metadata:
  name: {{ include "debug-playground.fullname" . }}
  labels:
    purpose: debug-playground
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 443
      protocol: UDP
  selector:
    name: z{{ include "debug-playground.fullname" . }}
