apiVersion: v1
kind: Service
metadata:
  name: {{ include "debug-playground.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 81
      protocol: TCP
  selector:
    name: incorrect
